[build]
  publish = "."
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    Referrer-Policy = "strict-origin-when-cross-origin"
